version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.22.1
    - 8.26.1
    - 8.27.0
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: laravel/jetstream
    versions:
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.2.1
    - 2.2.2
    - 2.2.3
    - 2.2.4
    - 2.2.5
    - 2.3.0
    - 2.3.1
    - 2.3.2
    - 2.3.3
  - dependency-name: livewire/livewire
    versions:
    - 2.3.13
    - 2.3.14
    - 2.3.15
    - 2.3.16
    - 2.3.17
    - 2.3.18
    - 2.3.8
    - 2.4.1
    - 2.4.2
    - 2.4.3
  - dependency-name: facade/ignition
    versions:
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.9
    - 2.6.0
    - 2.7.0
    - 2.8.2
  - dependency-name: laravel/sanctum
    versions:
    - 2.9.1
    - 2.9.2
    - 2.9.3
    - 2.9.4
  - dependency-name: laravel/dusk
    versions:
    - 6.11.3
    - 6.12.0
    - 6.14.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.3
  - dependency-name: phan/phan
    versions:
    - 4.0.2
